FROM alpine:3.13
COPY sqlboiler sqlboiler
COPY sqlboiler-psql sqlboiler-psql
COPY sqlboiler-mysql sqlboiler-mysql
COPY sqlboiler-mssql sqlboiler-mssql
# docker run sqlboiler:vX.X.X --wipe /sqlboiler-psq ...
ENTRYPOINT ["/sqlboiler"]